### PR TITLE
💖 Created CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by nchristopher**
As recommended by GitHub's [Community Standards](https://github.com/MarcusOtter/discord-needle/community), this pull request adds a `CODE_OF_CONDUCT.md` file.

### CODE REVIEW

**Review by c43721 — APPROVED** [review]
thank you for this :)

**Comment by MarcusOtter** [comment]
It'll take some time for me to go through this and modify/add/remove things I have in mind, but thank you for starting the process!

I have two code of conducts that I really like, Josh W Comeau's (for his courses, no public link afaik) and [Astro's](https://github.com/withastro/astro/blob/main/CODE_OF_CONDUCT.md)

I'll take some inspiration from those and make edits to this once I find the time to do so :)

**Comment by nchristopher** [comment]
> EDIT FOR ME: https://www.contributor-covenant.org/version/2/0/code_of_conduct/

FYI, this Code of Conduct is based off that one.

**Review by MarcusOtter — APPROVED** [review]
This was long overdue, sorry it took so long. I'm more familiar with the Contributor Covenant now, and have had time to read up on it and understand it. I pushed some minor changes (upgrading it to v2.1, and let prettier format it), hope that was okay. Thanks ✨

**Pull request merged**
