### PR TITLE
chore(deps): update dependenices to latest and use type imports

### PR DESCRIPTION
**Pull request by c43721**
it's 2022 and year old get-rid-of-type-only-imports

liberty also struck by updating the package to latest version(s)

### CODE REVIEW

**Comment by MarcusOtter** [comment]
Cool! I will double check that the package upgrades work, as many of these upgrades are major versions and breaking. I'm pretty limited on time atm but happy to merge this in a few days when I've verified that nothing breaks with it.

**Comment by c43721** [comment]
oh yeah this is like 10 major versions, no rush. It builds so I assume it works (as we all should)

**Comment by nchristopher** [comment]
Might be good to setup [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) in the future to get automatic PRs with `package.json` upgrades.

**Comment by c43721** [comment]
Converted to draft as I need to fix merge conflicts and update the package again

**Comment by MarcusOtter** [comment]
That's fine, I can fix these merge conflicts. I created them after all 😄

**Comment by c43721** [comment]
still needs another breaking update 😉

**Comment by c43721** [comment]
image
New deps

**Comment by c43721** [comment]
@MarcusOtter Ready for review + test

**Comment by MarcusOtter** [comment]
Nice! Are you okay with changing the license to AGPL 3.0 as outlined in #38 @c43721?

**Comment by c43721** [comment]
Have at it, no concerns here.

**Comment by MarcusOtter** [comment]
Tried the commands and ran the code, seems good. The one thing I did have to do was to change to ESLint VSC extension to a pre-release version since it didn't recognize the new syntax for importing types yet. Thank you for this contribution!

**Review by MarcusOtter — APPROVED** [review]
Tried this out locally and everything seems to work! I did have to upgrade my ESLint VSC extension to pre-release mode for it to recognize the new type syntax, but other than that no issues. Oh, and I changed the README to state the new minimum NodeJS version

**Pull request merged**
