### PR TITLE
fix(rename): limit thread names to less than 100 characters

### LINKED ISSUE #173: 🐛 Needle fails to rename thread if longer than 100 chars
### Describe the bug

From Dayhawk#6969 on Discord:
> Keep getting this message when trying to use /title, is this because of the update?
image

This is a previously known bug, but I've forgotten to make an issue about it. Discord has a limitation of 100 characters, and we should warn when users try to exceed that limit. We should also make sure to do the same character removal that Discord does, for example they remove `/`, `\`, and `:` (and probably others). Those should be removed before checking the length, and users should be warned that they have been removed.

### Steps to reproduce the bug

1. Run `/title` with 101 valid characters
2. See error
3. Run `/title` with 100 characters followed by any amount of slashes, backslashes, and colons
4. Title is still set (as the total amount is 100 valid characters at the end)

### Expected behavior

The bot should warn when users try to exceed the 100 character limit

### PR DESCRIPTION
**Pull request by c43721**
Fixes #173 by enforcing string limits before renaming the thread.

### CODE REVIEW

**Comment by MarcusOtter** [comment]
Do you know if we can use the `max_length` option yet with Discord.js? It was added ot the API last week
https://discord.com/developers/docs/change-log#min-and-max-length-for-command-options

Would be better UX knowing in advance!

**Comment by c43721** [comment]
not sure- don't think so because djs 13.9 isn't out?

**Comment by nchristopher** [comment]
discordjs/discord.js#8217 is under v13.9 - IMO, we should wait until then and limit the command itself for better UX.

**Comment by c43721** [comment]
of course it's already been merged :|

wake me up when djs updates

**Review by nchristopher — COMMENTED** [review]
Is it possible to use an option past it's max length? If not, we shouldn't have a separate error for it, because it would only happen from a bug in Discord's API.

**Comment by c43721** [comment]
@MarcusOtter Should we close in favor of #250 ?

**Comment by MarcusOtter** [comment]
Leave it open for a bit, I will implement these changes manually and add you as a co-author to those commits @c43721

**Comment by MarcusOtter** [comment]
Superseded by #250, added c4 as co-author there

**Pull request closed without merging**
