### PR TITLE
✨ Auto-thread slowmode option

### PR DESCRIPTION
**Pull request by nchristopher**
This pull request adds `slowmode` option to `/configure auto-threading` with the possible options:

- Off (DEFAULT)
- 5 seconds
- 30 seconds
- 1 minute
- 5 minutes
- 15 minutes
- 1 hour
- 6 hours

This option is used as an auto-thread's default slowmode.

The value for each option in the dropdown menu is the corresponding seconds as a string. This is converted & stored as a number in `configureAutothreading()`.

### CODE REVIEW

**Review by MarcusOtter — CHANGES_REQUESTED** [review]
Tested it and it seems like it is working well, but Needle requires additional permissions to set the slowmode (probably Manage Threads), and if it doesn't have those permissions it just does nothing when a message is sent. We should probably handle that more graciously. I'm thinking we should check that the bot has the required permissions both when you first invoke the command (and not enable auto-threading if the bot does not have required permissions), *and* when we try to create a thread (and probably respond publicly if Needle is missing permissions to do slowmode).

We should also add a note in the parameter description that it requires a certain permission if it's changed from the default.

**Comment by nchristopher** [comment]
We can easily upgrade Needle's permissions by sending an updated invite link. If you invite a bot that's already in your server, it will change its permissions.

**Comment by MarcusOtter** [comment]
It's also that I don't want to force people to add this permission. If you're not using this feature, there's no reason for Needle to have that permission.

**Review by MarcusOtter — APPROVED** [review]
Awesome, thank you so much for this, and sorry it took so long to review! Tried it out and it works great, code looks very good too. You're a star ✨

**Comment by MarcusOtter** [comment]
Ops, pulled the trigger a bit too early, the code was checking if Needle had Manage Threads every time you ran /configure auto-threading regardless of the input, added this: 

image

NOW it's perfect 😄

**Pull request merged**
